### ISSUE TITLE
pip installation fails on Windows

### ISSUE THREAD

**Issue by VinuraD** [andreArtelt/ceml#20]
It seems that some dependencies specified won't work on Windows (tried with Windows 10 Pro 21H2, virtualenv, and miniconda). It fails due to Jax-related installations it seems.  The dependencies work fine in Ubuntu though (20.04, Miniconda). I think it'd be worth mentioning this.

**Comment by andreArtelt** [comment]
Thanks for bringing this up. I updated the README.
Best,
André
