### ISSUE TITLE
How to handle the categorical features?

### ISSUE THREAD

**Issue by wangyongjie-ntu** [andreArtelt/ceml#7]
Can CEM support the categorical features? 
From the example, we can see both datasets do not include any categorical features.  
Could you help answer how to update the one-hot encoded features and convert back to the raw format?

Thanks.

**Comment by andreArtelt** [comment]
Hi,

unfortunately, CEML does not support categorical features :/
A potential promising approach for supporting categorical features is to use some kind of evolutionary/genetic optimization algorithm as suggested in https://arxiv.org/pdf/1905.07857.pdf Another interesting approach is described in https://arxiv.org/pdf/1909.09369.pdf

Note that CEML already comes with a prototypical implementation of an evolutionary/genetic optimization algorithm - see https://ceml.readthedocs.io/en/latest/ceml.optim.html#module-ceml.optim.ga
More information on how to use a custom optimization algorithm is described in the documentation https://ceml.readthedocs.io/en/latest/advanced.html#add-a-custom-optimizer

In my experience, dealing with categorical features can be very "unpleasant" and I found it always difficult to work with a model or data set containing categorical features - I usually try to avoid categorical features whenever possible. So far the approaches, described in the two linked papers, worked reasonable well for all my use-cases - although you loose theoretical guarantees and might not always find a "high quality" counterfactual.

Best wishes,
André

**Comment by wangyongjie-ntu** [comment]
Thanks for your reply. 
Hope to add the categorical feature support. 
The mixture of categorical and continuous datasets is more common in real-life. 

By the way, would you mind adding the good papers you think about XAI/CF to my repo [link]( https://github.com/wangyongjie-ntu/Awesome-explainable-AI/tree/master/counterfactuals)? Thanks very very much. 

Best regards,
Yongjie
