### ISSUE TITLE
Basic install option

### ISSUE THREAD

**Issue by whiletruelearn** [andreArtelt/ceml#8]
Hi ,

Sometimes we are using just the sklearn models for counter factuals and there is no need to use the torch dependency. Can we have different modes of installation so that not all libraries gets installed automatically with `install_requires`

**Comment by andreArtelt** [comment]
Hi,

I do not think that I will provide separate installations.
However, if you install the toolbox directly from the repository, you do not have to install torch or tensorflow if you use sklearn models only - simply exclude torch and tensorflow from `requirements.txt`

Best,
André
